"""PASS 17 — CASCADE TransJakarta BRT trunk corridors.

CASCADE.txt was not on disk; this is the structural source of truth from
the PASS 17 reconstruction spec. 12 trunks. No CAS-06. CAS-07 is
Puri Beta–Monas (NOT Pinang Ranti–Harjamukti).

AI is the digitizer. Geometry follows OSM arterials in roads.geojson and
existing TJ corridor centreline where the proposal reuses a ruas.
Bukan DED. Bukan existing TransJakarta.
"""

C = []


def add(**kw):
    C.append(kw)


# Control-point coordinates. Existing snaps (TJ/KRL/MRT/LRT) win in the
# rebuild engine when the name matches. These are on-corridor, not
# kecamatan centroids. Off-road spikes are snapped at build time.
NODES = {
    # CAS-01 Petojo – Pulo Gebang
    "Petojo": (106.81698, -6.16998, "tj_k3"),
    "Cideng": (106.8138, -6.1734, "jalan_cideng"),
    "Hasyim Ashari": (106.8118, -6.1762, "jalan_hasyim_ashari"),
    "Tanah Abang": (106.81079, -6.18653, "krl_tanah_abang"),
    "Kebon Kacang": (106.8148, -6.1938, "kh_mas_mansyur"),
    "KH Mas Mansyur": (106.8162, -6.1972, "kh_mas_mansyur"),
    "Karet Tengsin": (106.81600, -6.20086, "krl_karet"),
    "Satrio": (106.8218, -6.2145, "jl_satrio"),
    "Karet Kuningan": (106.8275, -6.2215, "jl_satrio_kuningan"),
    "Mall Ambassador": (106.8335, -6.2242, "jl_satrio"),
    "Casablanca": (106.8415, -6.2244, "jl_raya_casablanca"),
    "Dr Saharjo": (106.8476, -6.2145, "jl_saharjo"),
    "Pasar Rumput": (106.84112, -6.20713, "tj_k4"),
    "Manggarai Selatan": (106.85025, -6.21110, "krl_manggarai"),
    "Kampung Melayu": (106.86682, -6.22467, "tj_k5"),
    "Jatinegara": (106.86807, -6.22141, "tj_k5"),
    "Cipinang": (106.8820, -6.2148, "jl_ngurah_rai"),
    "BKT": (106.8987, -6.2135, "tj_stasiun_klender"),
    "Duren Sawit": (106.91188, -6.21441, "tj_k11"),
    "Pondok Kopi": (106.93054, -6.21669, "tj_k11"),
    "Penggilingan": (106.93961, -6.21413, "tj_k11"),
    "Walikota Jakarta Timur": (106.94537, -6.21254, "tj_k11"),
    "Pulo Gebang": (106.95265, -6.21270, "tj_k11"),
    # CAS-02 Pulo Gadung – Harapan Indah
    "Pulo Gadung": (106.90885, -6.18333, "tj_k2"),
    "Pemuda": (106.89165, -6.19349, "tj_pemuda_rawamangun"),
    "Rawa Terate": (106.9220, -6.1835, "jl_bekasi_raya"),
    "Cakung": (106.9379, -6.1830, "jl_bekasi_raya"),
    "Pasar Cakung": (106.9480, -6.1825, "jl_bekasi_raya"),
    "Cakung-Cilincing": (106.9314, -6.1296, "jl_cakung_cilincing_utara"),
    "Tipar Cakung": (106.9420, -6.1650, "jl_cakung_cilincing"),
    "Ujung Menteng": (106.9650, -6.1825, "jl_bekasi_raya"),
    "Raya Bekasi": (106.9690, -6.1832, "jl_bekasi_raya"),
    "Harapan Indah Boulevard": (106.9805, -6.1805, "harapan_indah"),
    "Harapan Indah": (106.9920, -6.1780, "harapan_indah"),
    "Transera": (106.9985, -6.1765, "transera_hi"),
    # CAS-03 JIS – Marunda
    "Senen": (106.84251, -6.17821, "tj_pasar_senen"),
    "Kemayoran": (106.85151, -6.15889, "tj_k14"),
    "JIExpo": (106.8444, -6.1470, "benyamin_sueb"),
    "Danau Sunter": (106.8680, -6.1380, "sunter"),
    "Jembatan Item": (106.85515, -6.13098, "tj_k14"),
    "JIS": (106.85587, -6.12669, "tj_k14"),
    "Sunter": (106.89076, -6.14290, "tj_k10"),
    "Kelapa Gading": (106.9050, -6.1575, "perintis_boulevard"),
    "Pegangsaan Dua": (106.9180, -6.1520, "kelapa_gading_timur"),
    "Sukapura": (106.9250, -6.1350, "cilincing"),
    "Cilincing": (106.9263, -6.1220, "jl_raya_cilincing"),
    "Semper": (106.9220, -6.1165, "semper"),
    "Akses Marunda": (106.9382, -6.1104, "jl_akses_marunda"),
    "Marunda Center": (106.9500, -6.1090, "marunda"),
    "Rusun Marunda": (106.9580, -6.1085, "marunda"),
    "Marunda": (106.9602, -6.1077, "jl_marunda_makmur"),
    # CAS-04 Lebak Bulus – Kalideres
    "Lebak Bulus": (106.77493, -6.28930, "mrt"),
    "Pondok Pinang": (106.77204, -6.28217, "tj_k8"),
    "Tanah Kusir": (106.78168, -6.25700, "tj_k8"),
    "Kebayoran Lama": (106.77751, -6.23834, "tj_k13"),
    "Cipulir": (106.76541, -6.23782, "tj_k13"),
    "Permata Hijau": (106.78325, -6.22143, "tj_k8"),
    "Simprug": (106.78647, -6.23394, "tj_k8"),
    "Arteri": (106.77761, -6.21840, "tj_k8"),
    "Pos Pengumben": (106.77226, -6.21294, "tj_k8"),
    "Kelapa Dua Sasak": (106.76953, -6.20555, "tj_k8"),
    "Kebon Jeruk": (106.76887, -6.19431, "tj_k8"),
    "Duri Kepa": (106.76842, -6.18527, "tj_k8"),
    "Kedoya": (106.76301, -6.16444, "jl_panjang"),
    "Kedoya Raya": (106.7620, -6.1895, "jl_kedoya_raya"),
    "Kedoya Selatan": (106.7643, -6.1750, "kedoya_raya"),
    "Kembangan": (106.7428, -6.1912, "jl_kembangan_barat"),
    "Meruya Selatan": (106.7390, -6.2035, "jl_meruya_selatan"),
    "Meruya": (106.7442, -6.1975, "jl_meruya_ilir"),
    "Puri Kembangan": (106.7424, -6.1899, "jl_puri_kencana"),
    "Walikota Jakarta Barat": (106.7288, -6.1725, "jl_lingkar_luar_barat"),
    "Rawa Buaya": (106.72619, -6.15392, "tj_k3"),
    "Cengkareng": (106.7205, -6.1542, "daan_mogot"),
    "Taman Palem": (106.7125, -6.1545, "daan_mogot"),
    "Kalideres": (106.70550, -6.15441, "tj_k3"),
    # CAS-05 Lebak Bulus – Pinang Ranti
    "TB Simatupang": (106.7953, -6.2940, "jl_simatupang"),
    "Cilandak": (106.8000, -6.2925, "jl_simatupang"),
    "Fatmawati": (106.79246, -6.29247, "mrt"),
    "Cilandak Town Square": (106.8145, -6.2920, "jl_simatupang"),
    "Ragunan": (106.81948, -6.30577, "tj_k6"),
    "Jati Padang": (106.8380, -6.2940, "jl_simatupang"),
    "Pasar Minggu Selatan": (106.8445, -6.2935, "simatupang"),
    "Gedong": (106.8508, -6.2988, "simatupang"),
    "Cijantung": (106.8578, -6.3035, "simatupang"),
    "Pasar Rebo": (106.8624, -6.3082, "raya_bogor"),
    "Flyover Raya Bogor": (106.86570, -6.30650, "tj_k7"),
    "Tanah Merdeka": (106.87391, -6.30805, "tj_k7"),
    "Kampung Rambutan": (106.88215, -6.30988, "tj_k7"),
    "TMII": (106.88058, -6.29290, "lrt"),
    "Pinang Ranti": (106.88634, -6.29108, "tj_k9"),
    # CAS-07 Puri Beta – Monas
    "Puri Beta": (106.72602, -6.23060, "tj_k13"),
    "Simpang Joglo": (106.7378, -6.2298, "jl_ciledug"),
    "Joglo Raya": (106.7388, -6.2068, "jl_meruya_selatan"),
    "Srengseng": (106.7575, -6.1978, "jl_meruya_ilir"),
    "Palmerah": (106.79711, -6.20820, "krl_palmerah"),
    "Petamburan": (106.8058, -6.1948, "ks_tubun"),
    "Slipi Palmerah": (106.79989, -6.20203, "tj_petamburan"),
    "Monas": (106.82240, -6.17640, "medan_merdeka"),
    # CAS-08 Monas – Puri Indah
    "Slipi": (106.7998, -6.2020, "s_parman"),
    "Kemanggisan": (106.79694, -6.18991, "tj_k9"),
    "Budi Raya": (106.7834, -6.1866, "jl_budi_raya"),
    "Meruya Ilir": (106.7530, -6.1980, "jl_meruya_ilir"),
    "Meruya Utara": (106.7450, -6.1920, "kembangan"),
    "Muchtar Raya": (106.7380, -6.1885, "kembangan_selatan"),
    "Kembangan Selatan": (106.7424, -6.1919, "jl_kembangan_barat"),
    "Puri Indah": (106.7341, -6.1900, "jl_puri_lingkar_luar"),
    # CAS-09 Pinang Ranti – Pulo Gadung
    "Lubang Buaya": (106.9005, -6.2895, "tmii_timur"),
    "Jatiwarna": (106.9125, -6.2785, "pondok_gede"),
    "Jatiwaringin": (106.9099, -6.2573, "jl_jati_waringin"),
    "Pondok Gede": (106.9139, -6.2845, "jl_pondok_gede"),
    "Pondok Kelapa": (106.9280, -6.2490, "kalimalang"),
    "Kalimalang": (106.9235, -6.2492, "jl_kalimalang"),
    "Pondok Bambu": (106.9038, -6.2215, "pahlawan_revolusi"),
    "Buaran": (106.92140, -6.21533, "krl_buaran"),
    # CAS-10 Marunda – Pulo Gebang
    "Raya Tugu": (106.9261, -6.1213, "jl_raya_cilincing"),
    "Rorotan": (106.9340, -6.1450, "cakung_cilincing"),
    "Stasiun Cakung": (106.95206, -6.21909, "krl_cakung"),
    # CAS-11 PGC – UI
    "PGC": (106.86570, -6.26190, "tj_k10"),
    "Cililitan": (106.86635, -6.26249, "tj_k7"),
    "Kramat Jati": (106.86663, -6.26882, "tj_k7"),
    "Trikora": (106.86803, -6.30196, "tj_k7"),
    "Kampung Tengah": (106.8672, -6.2845, "jl_raya_bogor"),
    "Raya Bogor": (106.8632, -6.3200, "jl_raya_bogor"),
    "Cilangkap": (106.8648, -6.3380, "jl_raya_bogor"),
    "Kelapa Dua": (106.8485, -6.3555, "jl_jasin"),
    "Akses UI": (106.8355, -6.3572, "jl_jasin"),
    "Universitas Indonesia": (106.8330, -6.3602, "krl_ui"),
    # CAS-12 UI – Galunggung
    "Lenteng Agung": (106.83482, -6.33062, "krl"),
    "Tanjung Barat": (106.83865, -6.30969, "krl"),
    "Pasar Minggu": (106.8440, -6.2835, "jl_pasar_minggu"),
    "Pejaten": (106.8455, -6.2725, "pasar_minggu_utara"),
    "Pasar Minggu Baru": (106.85110, -6.26430, "krl"),
    "Kalibata": (106.8520, -6.2560, "tmp_kalibata"),
    "Cawang KRL": (106.85867, -6.24255, "krl_cawang"),
    "Tebet Timur": (106.8575, -6.2350, "tebet_utara"),
    "Tebet": (106.85842, -6.22753, "krl_tebet"),
    "Manggarai": (106.85025, -6.21110, "krl"),
    "Galunggung": (106.82338, -6.20440, "tj_k4"),
}


def N(*names):
    return list(names)


# ---------------------------------------------------------------------------
# 12 corridors. CAS-06 deleted. Old CAS-07 Harjamukti deleted.
# ---------------------------------------------------------------------------

add(
    id="CAS-01",
    route_order=1,
    name="Petojo – Pulo Gebang",
    short="Petojo–Pulo Gebang",
    from_name="Petojo",
    to_name="Pulo Gebang",
    parent_route="",
    cascade_status="NEW_TRUNK",
    existing_transjakarta="PARTIAL",
    geometry_confidence="HIGH",
    road_alignment_confidence="HIGH",
    planning_note="Trase tengah–timur: Petojo–Tanah Abang–Casablanca–Kampung Melayu–BKT–Pulo Gebang. Ruas timur menumpang koridor TJ 11.",
    controls=N(
        "Petojo",
        "Cideng",
        "Hasyim Ashari",
        "Tanah Abang",
        "Kebon Kacang",
        "KH Mas Mansyur",
        "Karet Tengsin",
        "Satrio",
        "Karet Kuningan",
        "Mall Ambassador",
        "Casablanca",
        "Dr Saharjo",
        "Pasar Rumput",
        "Kampung Melayu",
        "Jatinegara",
        "Cipinang",
        "BKT",
        "Duren Sawit",
        "Pondok Kopi",
        "Penggilingan",
        "Walikota Jakarta Timur",
        "Pulo Gebang",
    ),
    road_by_pair=[
        ["Jalan Suryopranoto", "Jalan Cideng Barat", "Jalan Cideng Timur", "Jalan Balikpapan Raya"],
        ["Jalan Cideng Barat", "Jalan Cideng Timur", "Jalan KH. Hasyim Ashari", "Jalan Kyai Haji Hasyim Ashari"],
        ["Jalan KH. Hasyim Ashari", "Jalan Kyai Haji Hasyim Ashari", "Jalan Jatibaru Raya", "Jalan Kota Bambu"],
        ["Jalan Kyai Haji Mas Mansyur", "Jalan K.H. Mas Mansyur", "Jalan Jatibaru Raya"],
        ["Jalan Kyai Haji Mas Mansyur", "Jalan K.H. Mas Mansyur"],
        ["Jalan Kyai Haji Mas Mansyur", "Jalan Jenderal Sudirman"],
        ["Jalan Jenderal Sudirman", "Jalan Profesor Doktor Satrio"],
        ["Jalan Profesor Doktor Satrio"],
        ["Jalan Profesor Doktor Satrio", "Jalan Raya Casablanca"],
        ["Jalan Raya Casablanca", "Jalan Profesor Doktor Satrio"],
        ["Jalan Dokter Saharjo", "Jalan Raya Casablanca"],
        ["Jalan Dokter Saharjo", "TJ-K4", "Jalan Profesor Dokter Supomo SH"],
        ["Jalan Otto Iskandar Dinata", "TJ-K5", "TJ-K11", "Jalan Jatinegara Barat Raya"],
        ["TJ-K11", "TJ-K5", "Jalan Jatinegara Timur"],
        ["TJ-K11", "Jalan I Gusti Ngurah Rai"],
        ["TJ-K11", "Jalan I Gusti Ngurah Rai"],
        ["TJ-K11", "Jalan I Gusti Ngurah Rai"],
        ["TJ-K11", "Jalan I Gusti Ngurah Rai", "Jalan Raya Pondok Kopi"],
        ["TJ-K11", "Penggilingan Raya", "Jalan Dokter KRT Radjiman Widyodiningrat"],
        ["TJ-K11", "Jalan Pulo Gebang", "Jalan Raya Pulo Gebang"],
        ["TJ-K11", "Jalan Pulo Gebang"],
    ],
    anchors=N(
        "Petojo",
        "Tanah Abang",
        "Karet Tengsin",
        "Satrio",
        "Karet Kuningan",
        "Mall Ambassador",
        "Casablanca",
        "Dr Saharjo",
        "Pasar Rumput",
        "Kampung Melayu",
        "Jatinegara",
        "Cipinang",
        "BKT",
        "Duren Sawit",
        "Pondok Kopi",
        "Penggilingan",
        "Walikota Jakarta Timur",
        "Pulo Gebang",
    ),
)

add(
    id="CAS-02",
    route_order=2,
    name="Pulo Gadung – Harapan Indah",
    short="Pulo Gadung–Harapan Indah",
    from_name="Pulo Gadung",
    to_name="Harapan Indah",
    parent_route="TJ Koridor 2",
    cascade_status="EXTENSION",
    existing_transjakarta="PARTIAL",
    geometry_confidence="MEDIUM",
    road_alignment_confidence="MEDIUM",
    planning_note="Perpanjangan timur dari Pulo Gadung (induk koridor 2 Pulo Gadung–Monas) menuju Harapan Indah via Bekasi Raya. Bukan trase Monas. Pemuda ada di induk existing TJ 2, bukan di perpanjangan ini.",
    controls=N(
        "Pulo Gadung",
        "Rawa Terate",
        "Cakung",
        "Pasar Cakung",
        "Ujung Menteng",
        "Raya Bekasi",
        "Harapan Indah Boulevard",
        "Harapan Indah",
        "Transera",
    ),
    road_by_pair=[
        ["Jalan Bekasi Raya", "Jalan Perintis Kemerdekaan", "Jalan Pemuda"],
        ["Jalan Bekasi Raya"],
        ["Jalan Bekasi Raya"],
        ["Jalan Bekasi Raya"],
        ["Jalan Bekasi Raya"],
        ["Jalan Bekasi Raya", "Jalan Bulevar Ahmad Yani"],
        ["Jalan Bulevar Ahmad Yani", "Jalan Bulevar Selatan"],
        ["Jalan Bulevar Ahmad Yani"],
    ],
    anchors=N(
        "Pulo Gadung",
        "Rawa Terate",
        "Cakung",
        "Pasar Cakung",
        "Ujung Menteng",
        "Raya Bekasi",
        "Harapan Indah Boulevard",
        "Harapan Indah",
        "Transera",
    ),
)

add(
    id="CAS-03",
    route_order=3,
    name="JIS – Marunda",
    short="JIS–Marunda",
    from_name="JIS",
    to_name="Marunda",
    parent_route="TJ Koridor 14",
    cascade_status="EXTENSION",
    existing_transjakarta="PARTIAL",
    geometry_confidence="HIGH",
    road_alignment_confidence="HIGH",
    planning_note="Dari JIS ke timur laut via Sunter / Kelapa Gading / Cilincing / Akses Marunda. Senen dan Kemayoran ada di induk TJ 14 ke selatan, bukan dibalik ke utara pada trase CASCADE.",
    controls=N(
        "JIS",
        "Jembatan Item",
        "Sunter",
        "Kelapa Gading",
        "Pegangsaan Dua",
        "Sukapura",
        "Cilincing",
        "Semper",
        "Cakung-Cilincing",
        "Akses Marunda",
        "Marunda Center",
        "Rusun Marunda",
        "Marunda",
    ),
    road_by_pair=[
        ["TJ-K14", "Jalan Benyamin Sueb", "Jalan Yos Sudarso", "Jalan R. E. Martadinata"],
        ["Jalan Yos Sudarso", "TJ-K10"],
        ["Jalan Yos Sudarso", "Jalan Perintis Kemerdekaan"],
        ["Jalan Perintis Kemerdekaan"],
        ["Jalan Raya Cilincing Koja", "Jalan Cakung Cilincing Timur"],
        ["Jalan Raya Cilincing Koja", "Jalan Cakung Cilincing Timur"],
        ["Jalan Raya Cilincing Koja"],
        ["Jalan Cakung Cilincing Timur", "Jalan Akses Marunda"],
        ["Jalan Akses Marunda", "Jalan Raya Cilincing Koja"],
        ["Jalan Akses Marunda", "Jalan Marunda Bidara"],
        ["Jalan Marunda Bidara", "Jalan Marunda Makmur"],
        ["Jalan Marunda Makmur"],
    ],
    anchors=N(
        "JIS",
        "Jembatan Item",
        "Sunter",
        "Kelapa Gading",
        "Pegangsaan Dua",
        "Sukapura",
        "Cilincing",
        "Semper",
        "Cakung-Cilincing",
        "Akses Marunda",
        "Marunda Center",
        "Rusun Marunda",
        "Marunda",
    ),
)

add(
    id="CAS-04",
    route_order=4,
    name="Lebak Bulus – Kalideres",
    short="Lebak Bulus–Kalideres",
    from_name="Lebak Bulus",
    to_name="Kalideres",
    parent_route="TJ Koridor 8",
    cascade_status="EXTENSION",
    existing_transjakarta="PARTIAL",
    geometry_confidence="HIGH",
    road_alignment_confidence="HIGH",
    planning_note="Selatan–barat: Lebak Bulus–Kebayoran Lama–Pos Pengumben–Kembangan–Meruya–Daan Mogot–Kalideres. Berbeda dari CAS-08 (via Slipi).",
    controls=N(
        "Lebak Bulus",
        "Pondok Pinang",
        "Tanah Kusir",
        "Kebayoran Lama",
        "Cipulir",
        "Simprug",
        "Permata Hijau",
        "Arteri",
        "Pos Pengumben",
        "Kelapa Dua Sasak",
        "Kebon Jeruk",
        "Duri Kepa",
        "Kedoya Selatan",
        "Kedoya",
        "Kedoya Raya",
        "Kembangan",
        "Meruya",
        "Puri Kembangan",
        "Walikota Jakarta Barat",
        "Rawa Buaya",
        "Cengkareng",
        "Taman Palem",
        "Kalideres",
    ),
    road_by_pair=[
        ["TJ-K8", "Jalan Raden Ajeng Kartini", "Jalan Metro Pondok Indah", "Jalan RS Fatmawati"],
        ["TJ-K8", "Jalan Raya Kebayoran Lama", "Jalan Sultan Iskandar Muda"],
        ["TJ-K8", "Jalan Raya Kebayoran Lama", "TJ-K13"],
        ["TJ-K13", "Jalan Raya Kebayoran Lama", "Jalan Ciledug Raya"],
        ["TJ-K8", "Jalan Raya Kebayoran Lama", "Jalan Sultan Iskandar Muda"],
        ["TJ-K8", "Jalan Raya Kebayoran Lama"],
        ["TJ-K8", "Jalan Arteri Pos Pengumben", "Jalan Panjang Raya"],
        ["TJ-K8", "Jalan Arteri Pos Pengumben", "Jalan Panjang Raya"],
        ["Jalan Panjang Raya", "TJ-K8"],
        ["Jalan Panjang Raya"],
        ["Jalan Panjang Raya"],
        ["Jalan Panjang Raya", "Jalan Kedoya Raya"],
        ["Jalan Panjang Raya", "Jalan Kedoya Raya", "Jalan Kembangan Barat"],
        ["Jalan Kedoya Raya", "Jalan Kembangan Barat", "Jalan Meruya Ilir"],
        ["Jalan Kembangan Barat", "Jalan Lingkar Luar Barat", "Jalan Meruya Selatan", "Jalan Puri Kencana"],
        ["Jalan Meruya Ilir", "Jalan Meruya Selatan", "Jalan Puri Kencana"],
        ["Jalan Puri Kencana", "Jalan Puri Lingkar Luar", "Jalan Kembangan Barat"],
        ["Jalan Puri Lingkar Luar", "Jalan Lingkar Luar Barat", "Jalan Daan Mogot"],
        ["Jalan Lingkar Luar Barat", "Jalan Daan Mogot", "TJ-K3"],
        ["Jalan Daan Mogot", "TJ-K3"],
        ["Jalan Daan Mogot", "TJ-K3"],
        ["Jalan Daan Mogot", "TJ-K3"],
    ],
    anchors=N(
        "Lebak Bulus",
        "Pondok Pinang",
        "Kebayoran Lama",
        "Cipulir",
        "Permata Hijau",
        "Simprug",
        "Pos Pengumben",
        "Kelapa Dua Sasak",
        "Kebon Jeruk",
        "Duri Kepa",
        "Kedoya",
        "Kedoya Raya",
        "Kembangan",
        "Meruya",
        "Puri Kembangan",
        "Walikota Jakarta Barat",
        "Rawa Buaya",
        "Cengkareng",
        "Taman Palem",
        "Kalideres",
    ),
)

add(
    id="CAS-05",
    route_order=5,
    name="Lebak Bulus – Pinang Ranti",
    short="Lebak Bulus–Pinang Ranti",
    from_name="Lebak Bulus",
    to_name="Pinang Ranti",
    parent_route="",
    cascade_status="NEW_TRUNK",
    existing_transjakarta="PARTIAL",
    geometry_confidence="HIGH",
    road_alignment_confidence="HIGH",
    planning_note="Lingkar selatan via TB Simatupang – Ragunan – Cijantung – Pasar Rebo – Kampung Rambutan – TMII – Pinang Ranti.",
    controls=N(
        "Lebak Bulus",
        "Pondok Pinang",
        "Fatmawati",
        "TB Simatupang",
        "Cilandak",
        "Cilandak Town Square",
        "Ragunan",
        "Jati Padang",
        "Pasar Minggu Selatan",
        "Gedong",
        "Cijantung",
        "Pasar Rebo",
        "Flyover Raya Bogor",
        "Tanah Merdeka",
        "Kampung Rambutan",
        "TMII",
        "Pinang Ranti",
    ),
    road_by_pair=[
        ["TJ-K8", "Jalan Raden Ajeng Kartini", "Jalan Metro Pondok Indah"],
        ["Jalan RS Fatmawati", "Jalan Raden Ajeng Kartini"],
        ["Jalan RS Fatmawati", "Jalan Tahi Bonar Simatupang"],
        ["Jalan Tahi Bonar Simatupang"],
        ["Jalan Tahi Bonar Simatupang"],
        ["Jalan Tahi Bonar Simatupang", "Jalan Pangeran Antasari"],
        ["Jalan Tahi Bonar Simatupang"],
        ["Jalan Tahi Bonar Simatupang"],
        ["Jalan Tahi Bonar Simatupang"],
        ["Jalan Tahi Bonar Simatupang"],
        ["Jalan Tahi Bonar Simatupang", "Jalan Raya Bogor"],
        ["Jalan Raya Bogor", "TJ-K7"],
        ["TJ-K7", "Jalan Raya Bogor"],
        ["TJ-K7"],
        ["TJ-K7", "Jalan Taman Mini I"],
        ["Jalan Mayor Jenderal Sutoyo", "Jalan Taman Mini I", "TJ-K9"],
    ],
    anchors=N(
        "Lebak Bulus",
        "Pondok Pinang",
        "TB Simatupang",
        "Cilandak",
        "Cilandak Town Square",
        "Ragunan",
        "Jati Padang",
        "Pasar Minggu Selatan",
        "Gedong",
        "Cijantung",
        "Pasar Rebo",
        "Tanah Merdeka",
        "Kampung Rambutan",
        "TMII",
        "Pinang Ranti",
    ),
)

add(
    id="CAS-07",
    route_order=7,
    name="Puri Beta – Monas",
    short="Puri Beta–Monas",
    from_name="Puri Beta",
    to_name="Monas",
    parent_route="",
    cascade_status="NEW_TRUNK",
    existing_transjakarta="PARTIAL",
    geometry_confidence="MEDIUM",
    road_alignment_confidence="MEDIUM",
    planning_note="Trunk baru barat–pusat: Puri Beta–Joglo–Pos Pengumben–Palmerah–Tanah Abang–Monas. BUKAN Pinang Ranti–Harjamukti.",
    controls=N(
        "Puri Beta",
        "Simpang Joglo",
        "Joglo Raya",
        "Srengseng",
        "Pos Pengumben",
        "Palmerah",
        "Petamburan",
        "Tanah Abang",
        "Monas",
    ),
    road_by_pair=[
        ["Jalan Ciledug Raya", "TJ-K13"],
        ["Jalan Ciledug Raya", "Jalan Meruya Selatan", "TJ-K13"],
        ["Jalan Meruya Selatan", "Jalan Meruya Ilir", "Jalan Panjang Raya"],
        ["Jalan Meruya Ilir", "Jalan Arteri Pos Pengumben", "Jalan Panjang Raya", "TJ-K8"],
        ["Jalan Aipda Karel Satsuit Tubun", "Jalan Tentara Pelajar", "TJ-K8", "Jalan Panjang Raya"],
        ["Jalan Aipda Karel Satsuit Tubun", "Jalan Letnan Jenderal Siswondo Parman"],
        ["Jalan Aipda Karel Satsuit Tubun", "Jalan Kyai Haji Mas Mansyur", "Jalan Kota Bambu", "Jalan Jatibaru Raya"],
        ["Jalan Mohammad Husni Thamrin", "Jalan Medan Merdeka Barat", "Jalan Majapahit", "Jalan Jenderal Sudirman", "Jalan Kyai Haji Mas Mansyur"],
    ],
    anchors=N("Puri Beta", "Joglo Raya", "Srengseng", "Pos Pengumben", "Palmerah", "Petamburan", "Tanah Abang", "Monas"),
)

add(
    id="CAS-08",
    route_order=8,
    name="Monas – Puri Indah",
    short="Monas–Puri Indah",
    from_name="Monas",
    to_name="Puri Indah",
    parent_route="",
    cascade_status="NEW_TRUNK",
    existing_transjakarta="PARTIAL",
    geometry_confidence="HIGH",
    road_alignment_confidence="HIGH",
    planning_note="Pusat–barat via Slipi / Kemanggisan / Budi Raya / Kebon Jeruk / Meruya. Koridor terpisah dari CAS-04 dan CAS-07. Boleh beririsan di Tanah Abang / Monas.",
    controls=N(
        "Monas",
        "Tanah Abang",
        "Petamburan",
        "Slipi",
        "Kemanggisan",
        "Budi Raya",
        "Kebon Jeruk",
        "Meruya Ilir",
        "Meruya Utara",
        "Muchtar Raya",
        "Kembangan Selatan",
        "Puri Indah",
    ),
    road_by_pair=[
        ["Jalan Mohammad Husni Thamrin", "Jalan Medan Merdeka Barat", "Jalan Kyai Haji Mas Mansyur", "Jalan Jenderal Sudirman"],
        ["Jalan Kyai Haji Mas Mansyur", "Jalan Aipda Karel Satsuit Tubun", "Jalan Kota Bambu"],
        ["Jalan Aipda Karel Satsuit Tubun", "Jalan Letnan Jenderal Siswondo Parman"],
        ["Jalan Letnan Jenderal Siswondo Parman", "Jalan Kemanggisan Utama", "Jalan Kemanggisan Raya"],
        ["Jalan Kemanggisan Raya", "Jalan Budi Raya"],
        ["Jalan Budi Raya", "Jalan Panjang Raya", "Jalan Tanjung Duren Raya"],
        ["Jalan Panjang Raya", "Jalan Meruya Ilir", "Jalan Kedoya Raya"],
        ["Jalan Meruya Ilir", "Jalan Kembangan Barat"],
        ["Jalan Kembangan Barat", "Jalan Taman Aries", "Jalan Puri Lingkar Luar"],
        ["Jalan Kembangan Barat", "Jalan Puri Kencana", "Jalan Puri Lingkar Luar"],
        ["Jalan Puri Kencana", "Jalan Puri Lingkar Luar"],
    ],
    anchors=N(
        "Monas",
        "Tanah Abang",
        "Petamburan",
        "Slipi",
        "Kemanggisan",
        "Budi Raya",
        "Kebon Jeruk",
        "Meruya Ilir",
        "Meruya Utara",
        "Muchtar Raya",
        "Kembangan Selatan",
        "Puri Indah",
    ),
)

add(
    id="CAS-09",
    route_order=9,
    name="Pinang Ranti – Pulo Gadung",
    short="Pinang Ranti–Pulo Gadung",
    from_name="Pinang Ranti",
    to_name="Pulo Gadung",
    parent_route="",
    cascade_status="NEW_TRUNK",
    existing_transjakarta="NO",
    geometry_confidence="MEDIUM",
    road_alignment_confidence="MEDIUM",
    planning_note="Timur dalam: Pinang Ranti–Jatiwaringin–Pondok Kelapa–Duren Sawit–Pulo Gadung. BUKAN Pinang Ranti–Harjamukti.",
    controls=N(
        "Pinang Ranti",
        "Lubang Buaya",
        "Pondok Gede",
        "Jatiwarna",
        "Jatiwaringin",
        "Kalimalang",
        "Pondok Kelapa",
        "Pondok Bambu",
        "Duren Sawit",
        "Buaran",
        "Pulo Gadung",
    ),
    road_by_pair=[
        ["Jalan Pondok Gede", "Jalan Mayor Jenderal Sutoyo", "TJ-K9"],
        ["Jalan Pondok Gede"],
        ["Jalan Pondok Gede", "Jalan Jati Waringin"],
        ["Jalan Jati Waringin"],
        ["Jalan Jati Waringin", "Jalan Raya Kalimalang"],
        ["Jalan Raya Kalimalang"],
        ["Jalan Raya Kalimalang", "Jalan Pahlawan Revolusi", "Jalan I Gusti Ngurah Rai"],
        ["Jalan Pahlawan Revolusi", "Jalan I Gusti Ngurah Rai", "TJ-K11"],
        ["TJ-K11", "Jalan I Gusti Ngurah Rai"],
        ["Jalan Bekasi Timur", "Jalan Pemuda", "Jalan Perintis Kemerdekaan", "Jalan I Gusti Ngurah Rai"],
    ],
    anchors=N(
        "Pinang Ranti",
        "Lubang Buaya",
        "Pondok Gede",
        "Jatiwaringin",
        "Kalimalang",
        "Pondok Kelapa",
        "Pondok Bambu",
        "Duren Sawit",
        "Buaran",
        "Pulo Gadung",
    ),
)

add(
    id="CAS-10",
    route_order=10,
    name="Marunda – Pulo Gebang via Stasiun Cakung",
    short="Marunda–Pulo Gebang",
    from_name="Marunda",
    to_name="Pulo Gebang",
    parent_route="",
    cascade_status="NEW_TRUNK",
    existing_transjakarta="PARTIAL",
    geometry_confidence="HIGH",
    road_alignment_confidence="HIGH",
    planning_note="Timur laut: Marunda–Raya Tugu–Tipar Cakung–Penggilingan–Pulo Gebang. Arah balik wajib via Stasiun Cakung.",
    dual_direction=True,
    controls=N(
        "Marunda",
        "Marunda Center",
        "Akses Marunda",
        "Raya Tugu",
        "Rorotan",
        "Tipar Cakung",
        "Cakung",
        "Penggilingan",
        "Walikota Jakarta Timur",
        "Pulo Gebang",
    ),
    inbound_controls=N(
        "Pulo Gebang",
        "Stasiun Cakung",
        "Penggilingan",
        "Tipar Cakung",
        "Rorotan",
        "Raya Tugu",
        "Akses Marunda",
        "Marunda",
    ),
    road_by_pair=[
        ["Jalan Marunda Makmur", "Jalan Marunda Bidara"],
        ["Jalan Akses Marunda", "Jalan Marunda Bidara"],
        ["Jalan Akses Marunda", "Jalan Raya Cilincing Koja"],
        ["Jalan Cakung Cilincing Timur", "Jalan Cakung Cilincing Barat", "Jalan Raya Cilincing Koja"],
        ["Jalan Cakung Cilincing Timur", "Jalan Cakung Cilincing Barat"],
        ["Jalan Cakung Cilincing Barat", "Jalan Bekasi Raya"],
        ["Jalan Dokter KRT Radjiman Widyodiningrat", "Penggilingan Raya", "Jalan I Gusti Ngurah Rai"],
        ["TJ-K11", "Jalan Pulo Gebang", "Penggilingan Raya", "Jalan I Gusti Ngurah Rai"],
        ["TJ-K11", "Jalan Pulo Gebang", "Jalan Raya Pulo Gebang"],
    ],
    inbound_roads=[
        ["Jalan I Gusti Ngurah Rai", "TJ-K11", "Jalan Raya Pulo Gebang"],
        ["Jalan I Gusti Ngurah Rai", "TJ-K11", "Penggilingan Raya"],
        ["Penggilingan Raya", "Jalan Dokter KRT Radjiman Widyodiningrat", "Jalan Cakung Cilincing Barat"],
        ["Jalan Cakung Cilincing Barat", "Jalan Cakung Cilincing Timur"],
        ["Jalan Raya Cilincing Koja", "Jalan Cakung Cilincing Timur"],
        ["Jalan Akses Marunda", "Jalan Raya Cilincing Koja"],
        ["Jalan Akses Marunda", "Jalan Marunda Makmur"],
    ],
    anchors=N("Marunda", "Raya Tugu", "Rorotan", "Tipar Cakung", "Penggilingan", "Pulo Gebang", "Stasiun Cakung"),
)

add(
    id="CAS-11",
    route_order=11,
    name="PGC – Universitas Indonesia",
    short="PGC–UI",
    from_name="PGC",
    to_name="Universitas Indonesia",
    parent_route="",
    cascade_status="NEW_TRUNK",
    existing_transjakarta="PARTIAL",
    geometry_confidence="HIGH",
    road_alignment_confidence="HIGH",
    planning_note="Tenggara–Depok: PGC–Trikora–Pasar Rebo–Jalan Raya Bogor–Kelapa Dua–Akses UI–Universitas Indonesia. Bukan garis lurus.",
    controls=N(
        "PGC",
        "Cililitan",
        "Kramat Jati",
        "Kampung Tengah",
        "Trikora",
        "Pasar Rebo",
        "Raya Bogor",
        "Cilangkap",
        "Kelapa Dua",
        "Akses UI",
        "Universitas Indonesia",
    ),
    road_by_pair=[
        ["Jalan Dewi Sartika", "Jalan Raya Bogor", "TJ-K7"],
        ["Jalan Raya Bogor", "Jalan Dewi Sartika", "TJ-K7"],
        ["Jalan Raya Bogor", "TJ-K7"],
        ["Jalan Raya Bogor", "TJ-K7"],
        ["Jalan Raya Bogor"],
        ["Jalan Raya Bogor"],
        ["Jalan Raya Bogor"],
        ["Jalan Raya Bogor", "Jalan Komjen Polisi Mohammad Jasin", "Jalan Komjen Pol. M. Jasin"],
        ["Jalan Komjen Polisi Mohammad Jasin", "Jalan Komjen Pol. M. Jasin", "Jalan Raya Margonda"],
        ["Jalan Raya Margonda", "Jalan Lenteng Agung Raya"],
    ],
    anchors=N("PGC", "Cililitan", "Kramat Jati", "Kampung Tengah", "Trikora", "Pasar Rebo", "Raya Bogor", "Cilangkap", "Kelapa Dua", "Akses UI", "Universitas Indonesia"),
)

add(
    id="CAS-12",
    route_order=12,
    name="Universitas Indonesia – Galunggung",
    short="UI–Galunggung",
    from_name="Universitas Indonesia",
    to_name="Galunggung",
    parent_route="",
    cascade_status="NEW_TRUNK",
    existing_transjakarta="PARTIAL",
    geometry_confidence="HIGH",
    road_alignment_confidence="HIGH",
    planning_note="Depok–pusat selatan: UI–Lenteng Agung–Pasar Minggu–Tebet–Galunggung. Bertemu CAS-11 di UI, tidak digabung.",
    controls=N(
        "Universitas Indonesia",
        "Akses UI",
        "Lenteng Agung",
        "Tanjung Barat",
        "Pasar Minggu",
        "Pejaten",
        "Pasar Minggu Baru",
        "Kalibata",
        "Cawang KRL",
        "Tebet Timur",
        "Tebet",
        "Manggarai",
        "Pasar Rumput",
        "Galunggung",
    ),
    road_by_pair=[
        ["Jalan Raya Margonda"],
        ["Jalan Lenteng Agung Raya", "Jalan Lenteng Agung Barat", "Jalan Layang Lenteng Agung"],
        ["Jalan Lenteng Agung Raya", "Jalan Tanjung Barat", "Jalan Raya Tanjung Barat"],
        ["Jalan Pasar Minggu Raya", "Jalan Tanjung Barat"],
        ["Jalan Pasar Minggu Raya"],
        ["Jalan TMP Kalibata", "Jalan Pasar Minggu Raya"],
        ["Jalan TMP Kalibata", "Jalan Letnan Jenderal MT Haryono"],
        ["Jalan Letnan Jenderal MT Haryono", "Jalan Profesor Dokter Supomo SH", "TJ-K9"],
        ["Jalan Profesor Dokter Supomo SH", "Jalan Dokter Saharjo"],
        ["Jalan Profesor Dokter Supomo SH", "Jalan Dokter Saharjo"],
        ["Jalan Dokter Saharjo", "TJ-K4", "Jalan Sultan Agung"],
        ["TJ-K4", "Jalan Dokter Saharjo", "Jalan Galunggung"],
        ["Jalan Galunggung", "TJ-K4", "Jalan Profesor Doktor Satrio"],
    ],
    anchors=N(
        "Universitas Indonesia",
        "Lenteng Agung",
        "Tanjung Barat",
        "Pasar Minggu",
        "Pejaten",
        "Pasar Minggu Baru",
        "Kalibata",
        "Tebet",
        "Manggarai",
        "Galunggung",
    ),
)

CORRIDORS = C
assert [c["id"] for c in CORRIDORS] == [
    "CAS-01",
    "CAS-02",
    "CAS-03",
    "CAS-04",
    "CAS-05",
    "CAS-07",
    "CAS-08",
    "CAS-09",
    "CAS-10",
    "CAS-11",
    "CAS-12",
], "Network must be exactly the 12 final IDs"
assert all(c["id"] != "CAS-06" for c in CORRIDORS)
assert CORRIDORS[5]["from_name"] == "Puri Beta" and CORRIDORS[5]["to_name"] == "Monas"
assert "Kelapa Dua" in CORRIDORS[9]["anchors"]
