"""PASS 16 corridor dictionary — structure from MASTERPLAN.txt / PASS 16 spec.

MASTERPLAN.txt was not on disk; this is the structural source of truth used
for digitization. NODE_COORDS place route nodes on the documented corridor
spine (bukan centroid kecamatan). Existing connections snap from KRL/MRT/LRT.
"""

# node tuple: name, node_type, station_conf, notes
# node_type: STATION | ROUTE_NODE | REFERENCE | EXISTING_CONNECTION | DEPOT

C = []


def add(**kw):
    C.append(kw)


# Corridor-placed coordinates. Existing rail snaps win for EXISTING_CONNECTION
# except MRT 2A names that collide with KRL (Sawah Besar / Mangga Besar / Kota).
NODE_COORDS = {
    # KRL Parung Panjang–Citayam on-spine (Rumpin bukan centroid -6.456)
    "Dangdang": (106.6000, -6.3550, "corridor_PP_Citayam"),
    "Rumpin": (106.6380, -6.3750, "corridor_PP_Citayam"),
    "Gunung Sindur": (106.6820, -6.3900, "corridor_PP_Citayam"),
    "Cogreg": (106.7100, -6.4050, "corridor_PP_Citayam"),
    "Parung": (106.7330, -6.4210, "corridor_PP_Citayam"),
    "Arco": (106.7450, -6.4150, "corridor_PP_Citayam"),
    "Rawa": (106.7550, -6.4080, "corridor_PP_Citayam"),
    "Sawangan": (106.7700, -6.4000, "corridor_PP_Citayam"),
    # Outer ring
    "Kembang Kuning": (106.9380, -6.4380, "corridor_outer_ring"),
    "Cileungsi": (106.9920, -6.4020, "corridor_outer_ring"),
    "Jatisari": (107.0700, -6.3200, "corridor_outer_ring"),
    # Outer ring — kawasan sepanjang trase (nama indikatif, bukan daftar resmi penumpang)
    "Klapanunggal": (106.9220, -6.4520, "corridor_outer_ring"),
    "Mekarsari": (107.0150, -6.3850, "corridor_outer_ring"),
    "Narogong": (107.0300, -6.3600, "corridor_outer_ring"),
    "Setu": (107.0500, -6.3400, "corridor_outer_ring"),
    "Cikarang Utara": (107.1430, -6.2280, "corridor_outer_ring"),
    "Sukadanau": (107.1100, -6.1700, "corridor_outer_ring"),
    "Babelan": (107.0500, -6.1320, "corridor_outer_ring"),
    "Kebalen": (107.0200, -6.1280, "corridor_outer_ring"),
    "Tarumajaya": (106.9900, -6.1220, "corridor_outer_ring"),
    "Marunda": (106.9650, -6.1180, "corridor_outer_ring"),
    "Cilincing": (106.9400, -6.1150, "corridor_outer_ring"),
    "Semper": (106.9200, -6.1130, "corridor_outer_ring"),
    "Koja": (106.9000, -6.1110, "corridor_outer_ring"),
    # MRT 2A construction corridor (bukan stasiun KRL sejalan)
    "Thamrin": (106.82285, -6.18655, "construction_MH_Thamrin"),
    "Monas": (106.82240, -6.17640, "construction_Medan_Merdeka_Barat"),
    "Harmoni": (106.81950, -6.16640, "construction_Majapahit"),
    "Sawah Besar": (106.81870, -6.15580, "construction_Gajah_Mada"),
    "Mangga Besar": (106.81840, -6.14940, "construction_Hayam_Wuruk"),
    "Glodok": (106.81720, -6.14280, "construction_Hayam_Wuruk"),
    "Kota": (106.81480, -6.13770, "construction_near_Jakarta_Kota"),
    # MRT 2B
    "Mangga Dua": (106.82750, -6.13500, "corridor_2B_Mangga_Dua"),
    "Ancol Marina": (106.83000, -6.11850, "corridor_2B"),
    "Ancol Barat": (106.81200, -6.11650, "corridor_2B_depot"),
    # MRT 3 west — Daan Mogot / Tangerang, bukan centroid kecamatan
    "Cibadak Tangerang": (106.5000, -6.1960, "corridor_EW_west"),
    "Pasir Gadung": (106.5350, -6.2000, "corridor_EW_west"),
    "Kadu": (106.5720, -6.1940, "corridor_EW_west"),
    "Bencongan": (106.6020, -6.1860, "corridor_EW_west"),
    "Kelapa Dua Tangerang": (106.6280, -6.1800, "corridor_EW_west"),
    "Danau Ranau": (106.6480, -6.1750, "corridor_EW_west"),
    "Kebon Nanas": (106.6580, -6.1730, "corridor_EW_west"),
    "Kunciran": (106.6780, -6.1720, "corridor_EW_west"),
    "Karang Tengah": (106.6950, -6.1700, "corridor_EW_west"),
    "Hasyim Asy'ari": (106.7100, -6.1690, "corridor_EW_west"),
    "Kembangan": (106.7400, -6.1680, "corridor_EW_Daan_Mogot"),
    "Kembangan 2": (106.7520, -6.1660, "corridor_EW_Daan_Mogot"),
    "Roxy": (106.7970, -6.1665, "corridor_EW"),
    "Petojo": (106.8080, -6.1690, "corridor_EW"),
    "Cideng": (106.8140, -6.1750, "corridor_EW"),
    "Kebon Sirih": (106.8310, -6.1855, "corridor_EW"),
    "Kwitang": (106.8400, -6.1835, "corridor_EW"),
    "Senen": (106.8445, -6.1760, "corridor_EW"),
    "Galur": (106.8550, -6.1750, "corridor_EW"),
    "Cempaka Baru": (106.8620, -6.1680, "corridor_EW"),
    "Sumur Batu": (106.8720, -6.1630, "corridor_EW"),
    "Kelapa Gading Barat": (106.8880, -6.1580, "corridor_EW"),
    "Kelapa Gading Timur": (106.9050, -6.1575, "corridor_EW"),
    "Perintis": (106.9100, -6.1680, "corridor_EW"),
    "Pulo Gadung": (106.9080, -6.1830, "corridor_EW"),
    "Penggilingan": (106.9320, -6.1880, "corridor_EW"),
    "Cakung Barat": (106.9450, -6.1850, "corridor_EW"),
    "Pulo Gebang": (106.9580, -6.1850, "corridor_EW"),
    "Ujung Menteng": (106.9650, -6.1830, "corridor_EW"),
    "Kalibaru Bekasi": (106.9780, -6.1880, "corridor_EW_east"),
    "Medan Satria": (106.9900, -6.1900, "corridor_EW_east"),
    "Harapan Baru": (107.0180, -6.2050, "corridor_EW_east"),
    "Karang Satria": (107.0480, -6.2180, "corridor_EW_east"),
    "Sumber Jaya": (107.0650, -6.2320, "corridor_EW_east"),
    "Wanajaya": (107.1120, -6.2520, "corridor_EW_east"),
    # MRT 4 — bukan Pasar Minggu
    "Antasari": (106.8080, -6.2910, "corridor_F4_Antasari"),
    "Ampera": (106.8220, -6.2880, "corridor_F4"),
    "Warung Jati": (106.8320, -6.2780, "corridor_F4"),
    "Ranco": (106.8520, -6.3080, "corridor_F4"),
    "Raya Bogor": (106.8680, -6.3070, "corridor_F4"),
    "Tanah Merdeka": (106.8760, -6.3090, "corridor_F4"),
    # LRT Jakarta
    "Rawamangun": (106.8860, -6.1950, "corridor_1B_Pemuda"),
    "Pramuka BPKP": (106.8720, -6.1960, "corridor_1B_Pramuka"),
    "Pasar Pramuka": (106.8600, -6.1980, "corridor_1B_Pramuka"),
    "Matraman": (106.8580, -6.2060, "corridor_1B_Pramuka"),
    "Kelapa Nias": (106.9060, -6.1530, "corridor_2A_boulevard"),
    "Boulevard Gading": (106.8980, -6.1460, "corridor_2A"),
    "Sunter Timur": (106.8900, -6.1350, "corridor_2A_Yos_Sudarso"),
    "Gelanggang Remaja": (106.8800, -6.1240, "corridor_2A"),
    "Sunter Barat": (106.8700, -6.1180, "corridor_2A"),
    "JIS": (106.86096, -6.12507, "JIS_stadium"),
    "Pademangan": (106.8350, -6.1260, "corridor_3A"),
    "Pondok Bambu": (106.9027, -6.2380, "corridor_3B"),
    # LRT Bogor — Jagorawi, bukan centroid Gunung Putri timur
    "Cimanggis": (106.8880, -6.3850, "corridor_bogor_jagorawi"),
    "Gunung Putri": (106.8900, -6.4200, "corridor_bogor_jagorawi"),
    "Cibinong": (106.8680, -6.4680, "corridor_bogor_jagorawi"),  # kawasan di Jagorawi, bukan titik KRL
    "Sirkuit Sentul": (106.8580, -6.5300, "corridor_bogor"),
    "Sentul City": (106.8620, -6.5600, "corridor_bogor"),
    "Baranangsiang": (106.8160, -6.6010, "terminus_terminal_baranangsiang"),
    "Cisalak": (106.8920, -6.3790, "corridor_bogor_jagorawi"),
    "Jagakarsa": (106.8282, -6.3300, "corridor_09"),
    "Transyogi": (106.9440, -6.3880, "corridor_09"),
    "Nagrak": (106.9680, -6.3950, "corridor_09"),
    "Pulogadung": (106.9080, -6.1980, "corridor_2B_Ngurah_Rai"),
    "Kayu Putih": (106.9070, -6.1920, "corridor_2B"),
    "Gunung Sahari": (106.8310, -6.1330, "corridor_3A"),
}


add(
    id="KRL_PP_CITAYAM",
    mode="krl",
    name="KRL Parung Panjang–Citayam",
    short="Parung Panjang–Citayam",
    from_node="Parung Panjang",
    to_node="Citayam",
    status="MASTERPLAN",
    structure="NOT_SPECIFIED",
    source="BPTJ Review Trase",
    source_year=2022,
    source_type="BPTJ_STUDY",
    source_url="https://bptj.dephub.go.id",
    geometry_confidence="MEDIUM",
    alignment_confidence="MEDIUM",
    digitization_level="L3",
    digitization_method="DOCUMENT_RECONSTRUCTION + ROAD_REFERENCE",
    passenger_status="PASSENGER_PROPOSED",
    length_source_km=31.73,
    road_refs=["Jalan Raya Parung—Ciputat"],
    spine_strategy="on_corridor",
    spine=[
        [106.56869, -6.34425],
        [106.6000, -6.3550],
        [106.6380, -6.3750],
        [106.6820, -6.3900],
        [106.7100, -6.4050],
        [106.7330, -6.4210],
        [106.7450, -6.4150],
        [106.7550, -6.4080],
        [106.7700, -6.4000],
        [106.80206, -6.45003],
    ],
    nodes=[
        ("Parung Panjang", "EXISTING_CONNECTION", "HIGH", "KRL Green existing"),
        ("Dangdang", "ROUTE_NODE", "MEDIUM", "kawasan, bukan station"),
        ("Rumpin", "STATION", "MEDIUM", "stasiun rencana kawasan Rumpin"),
        ("Gunung Sindur", "STATION", "MEDIUM", ""),
        ("Cogreg", "STATION", "MEDIUM", ""),
        ("Parung", "STATION", "HIGH", ""),
        ("Arco", "STATION", "MEDIUM", ""),
        ("Rawa", "ROUTE_NODE", "LOW", "bukan station"),
        ("Sawangan", "ROUTE_NODE", "MEDIUM", "bukan station"),
        ("Citayam", "EXISTING_CONNECTION", "HIGH", "KRL Bogor existing"),
    ],
)

add(
    id="OUTER_RING_RAIL",
    mode="rail",
    name="Outer Ring Railway Nambo–Cikarang–Tanjung Priok",
    short="Outer Ring",
    from_node="Nambo",
    to_node="Tanjung Priok",
    status="PLANNED",
    structure="NOT_SPECIFIED",
    source="RTRW / BPTJ Review Trase",
    source_year=2022,
    source_type="RTRW",
    geometry_confidence="LOW",
    alignment_confidence="LOW",
    digitization_level="L2",
    digitization_method="DOCUMENT_RECONSTRUCTION",
    passenger_status="UNCERTAIN",
    service_type="OUTER_RING_RAILWAY",
    road_refs=["Jalan Raya Narogong", "Jalan Tol Cimanggis–Cibitung", "Jalan Tol Cibitung–Cilincing", "Jalan Tol Akses Tanjung Priok"],
    spine=[
        [106.90552, -6.46682],
        [106.9380, -6.4380],
        [106.9920, -6.4020],
        [107.0700, -6.3200],
        [107.14576, -6.25555],
        [107.1400, -6.2000],
        [107.0800, -6.1400],
        [106.9400, -6.1150],
        [106.88145, -6.11060],
    ],
    nodes=[
        ("Nambo", "EXISTING_CONNECTION", "HIGH", "KRL Nambo existing; terminus / interchange"),
        ("Klapanunggal", "STATION", "LOW", "indikatif: kawasan Klapanunggal sepanjang trase Nambo–Cileungsi"),
        ("Kembang Kuning", "STATION", "MEDIUM", "disebut dalam trase outer ring; bukan stasiun KRL existing"),
        ("Cileungsi", "STATION", "MEDIUM", "kawasan Cileungsi — simpul trase"),
        ("Mekarsari", "STATION", "LOW", "indikatif: kawasan Mekarsari (peta JUTPI / koridor Cileungsi)"),
        ("Narogong", "STATION", "LOW", "indikatif: koridor Jalan Raya Narogong"),
        ("Setu", "STATION", "LOW", "indikatif: kawasan Setu antara Cileungsi dan Cikarang"),
        ("Jatisari", "STATION", "LOW", "kawasan antara Cileungsi dan Cikarang"),
        ("Cikarang", "EXISTING_CONNECTION", "HIGH", "KRL Cikarang — interchange"),
        ("Cikarang Utara", "STATION", "LOW", "indikatif: kawasan industri Cikarang Utara / Jababeka"),
        ("Sukadanau", "STATION", "LOW", "indikatif: kawasan Sukadanau / Cibitung utara (tol Cibitung–Cilincing)"),
        ("Babelan", "STATION", "LOW", "indikatif: kawasan Babelan"),
        ("Kebalen", "STATION", "LOW", "indikatif: kawasan Kebalen"),
        ("Tarumajaya", "STATION", "LOW", "indikatif: kawasan Tarumajaya"),
        ("Marunda", "STATION", "LOW", "indikatif: kawasan Marunda"),
        ("Cilincing", "STATION", "LOW", "indikatif: kawasan Cilincing"),
        ("Semper", "STATION", "LOW", "indikatif: kawasan Semper"),
        ("Koja", "STATION", "LOW", "indikatif: kawasan Koja"),
        ("Tanjung Priok", "EXISTING_CONNECTION", "HIGH", "KRL Tanjung Priok — terminus / interchange"),
    ],
)

add(
    id="MRT_2A",
    mode="mrt",
    name="MRT North-South Fase 2A Bundaran HI–Kota",
    short="MRT 2A",
    from_node="Bundaran HI",
    to_node="Kota",
    status="CONSTRUCTION",
    structure="UNDERGROUND",
    structure_note="Operator: 7 stasiun bawah tanah; satu sumber menyebut Kota at-grade. structure_latest=UNDERGROUND.",
    source="PT MRT Jakarta (Perseroda)",
    source_year=2026,
    source_type="OFFICIAL_OPERATOR",
    source_url="https://jakartamrt.co.id",
    geometry_confidence="HIGH",
    alignment_confidence="HIGH",
    digitization_level="L4",
    digitization_method="DOCUMENT_RECONSTRUCTION + ROAD_REFERENCE",
    passenger_status="PASSENGER_CONFIRMED",
    length_source_km=5.8,
    road_refs=[
        "Jalan Mohammad Husni Thamrin",
        "Jalan Medan Merdeka Barat",
        "Jalan Majapahit",
        "Jalan Gajah Mada",
        "Jalan Hayam Wuruk",
    ],
    spine=[
        [106.82306, -6.19185],
        [106.82285, -6.18655],
        [106.82240, -6.17640],
        [106.81950, -6.16640],
        [106.81870, -6.15580],
        [106.81840, -6.14940],
        [106.81720, -6.14280],
        [106.81480, -6.13770],
    ],
    nodes=[
        ("Bundaran HI", "EXISTING_CONNECTION", "HIGH", "MRT existing terminus"),
        ("Thamrin", "STATION", "HIGH", "simpul MRT 2A / MRT 3"),
        ("Monas", "STATION", "HIGH", ""),
        ("Harmoni", "STATION", "HIGH", ""),
        ("Sawah Besar", "STATION", "HIGH", ""),
        ("Mangga Besar", "STATION", "HIGH", ""),
        ("Glodok", "STATION", "HIGH", ""),
        ("Kota", "STATION", "HIGH", "near Jakarta Kota KRL"),
    ],
)

add(
    id="MRT_2B",
    mode="mrt",
    name="MRT North-South Fase 2B Kota–Ancol Barat",
    short="MRT 2B",
    from_node="Kota",
    to_node="Ancol Barat",
    status="FS",
    structure="UNDER_REVIEW",
    source="PT MRT Jakarta (Perseroda)",
    source_year=2026,
    source_type="OFFICIAL_OPERATOR",
    geometry_confidence="MEDIUM",
    alignment_confidence="MEDIUM",
    digitization_level="L3",
    digitization_method="DOCUMENT_RECONSTRUCTION + ROAD_REFERENCE",
    passenger_status="PASSENGER_PROPOSED",
    length_source_km=5.2,
    road_refs=["Jalan Gunung Sahari Raya", "Jalan Lodan Raya"],
    spine=[
        [106.81480, -6.13770],
        [106.82750, -6.13500],
        [106.83000, -6.11850],
        [106.81200, -6.11650],
    ],
    nodes=[
        ("Kota", "EXISTING_CONNECTION", "HIGH", "lanjutan 2A"),
        ("Mangga Dua", "STATION", "HIGH", ""),
        ("Ancol Marina", "STATION", "MEDIUM", "nomenklatur PASS 16; operator juga menyebut Ancol / Gunung Sahari"),
        ("Ancol Barat", "DEPOT", "MEDIUM", "depot / terminus"),
    ],
)

add(
    id="MRT_3",
    mode="mrt",
    name="MRT East-West Fase 3 Balaraja–Cikarang",
    short="MRT East-West",
    from_node="Balaraja",
    to_node="Cikarang",
    status="MASTERPLAN",
    structure="UNDER_REVIEW",
    source="JICA / MRT Jakarta East-West Line",
    source_year=2024,
    source_type="JICA_STUDY",
    geometry_confidence="MEDIUM",
    alignment_confidence="MEDIUM",
    digitization_level="L3",
    digitization_method="DOCUMENT_RECONSTRUCTION + ROAD_REFERENCE",
    passenger_status="PASSENGER_PROPOSED",
    length_source_km=84.1,
    road_refs=[
        "Jalan Tol Kamal–Balaraja",
        "Jalan Tol Jakarta–Merak",
        "Jalan Daan Mogot",
        "Jalan Kyai Tapa",
        "Jalan Kyai Haji Hasyim Ashari",
        "Jalan Kebon Sirih",
        "Jalan Letnan Jenderal Suprapto",
        "Jalan Perintis Kemerdekaan",
        "Jalan Jenderal Ahmad Yani",
        "Penggilingan Raya",
        "Jalan Bekasi Raya",
        "Jalan Tol Cibitung–Cilincing",
    ],
    spine=[
        [106.4628, -6.1911],
        [106.5000, -6.1960],
        [106.5350, -6.2000],
        [106.5720, -6.1940],
        [106.6020, -6.1860],
        [106.6280, -6.1800],
        [106.6480, -6.1750],
        [106.6580, -6.1730],
        [106.6640, -6.1724],
        [106.6780, -6.1720],
        [106.6950, -6.1700],
        [106.7025, -6.1662],
        [106.7228, -6.1628],
        [106.7400, -6.1680],
        [106.7520, -6.1660],
        [106.7716, -6.1612],
        [106.7873, -6.1620],
        [106.7970, -6.1665],
        [106.8080, -6.1690],
        [106.8140, -6.1750],
        [106.82285, -6.18655],
        [106.8310, -6.1855],
        [106.8400, -6.1835],
        [106.8445, -6.1760],
        [106.8550, -6.1750],
        [106.8620, -6.1680],
        [106.8720, -6.1630],
        [106.8880, -6.1580],
        [106.9050, -6.1575],
        [106.9100, -6.1680],
        [106.9080, -6.1830],
        [106.9320, -6.1880],
        [106.9450, -6.1850],
        [106.9580, -6.1850],
        [106.9650, -6.1830],
        [106.9780, -6.1880],
        [106.9900, -6.1900],
        [107.0180, -6.2050],
        [107.0480, -6.2180],
        [107.0650, -6.2320],
        [107.0832, -6.2450],
        [107.1120, -6.2520],
        [107.14576, -6.25555],
    ],
    nodes=[
        ("Balaraja", "STATION", "MEDIUM", ""),
        ("Cibadak Tangerang", "REFERENCE", "LOW", "nomenklatur Cibadak"),
        ("Pasir Gadung", "REFERENCE", "LOW", ""),
        ("Kadu", "REFERENCE", "LOW", ""),
        ("Bencongan", "REFERENCE", "LOW", ""),
        ("Kelapa Dua Tangerang", "REFERENCE", "LOW", ""),
        ("Danau Ranau", "REFERENCE", "LOW", ""),
        ("Kebon Nanas", "REFERENCE", "LOW", ""),
        ("Kunciran", "REFERENCE", "MEDIUM", ""),
        ("Karang Tengah", "REFERENCE", "MEDIUM", ""),
        ("Batu Ceper", "EXISTING_CONNECTION", "HIGH", "KRL Tangerang"),
        ("Hasyim Asy'ari", "REFERENCE", "MEDIUM", ""),
        ("Kembangan", "STATION", "HIGH", ""),
        ("Kembangan 2", "REFERENCE", "LOW", ""),
        ("Rawa Buaya", "EXISTING_CONNECTION", "HIGH", "KRL"),
        ("Kalideres", "EXISTING_CONNECTION", "HIGH", "KRL"),
        ("Pesing", "EXISTING_CONNECTION", "HIGH", "KRL"),
        ("Grogol", "STATION", "HIGH", "KRL + MRT EW"),
        ("Roxy", "STATION", "MEDIUM", ""),
        ("Petojo", "REFERENCE", "MEDIUM", ""),
        ("Cideng", "STATION", "MEDIUM", ""),
        ("Thamrin", "STATION", "HIGH", "interchange MRT 2A"),
        ("Kebon Sirih", "STATION", "MEDIUM", ""),
        ("Kwitang", "STATION", "MEDIUM", ""),
        ("Senen", "STATION", "HIGH", ""),
        ("Galur", "STATION", "MEDIUM", ""),
        ("Cempaka Baru", "STATION", "MEDIUM", ""),
        ("Sumur Batu", "STATION", "MEDIUM", ""),
        ("Kelapa Gading Barat", "STATION", "MEDIUM", ""),
        ("Kelapa Gading Timur", "STATION", "MEDIUM", ""),
        ("Perintis", "REFERENCE", "MEDIUM", ""),
        ("Pulo Gadung", "STATION", "HIGH", ""),
        ("Penggilingan", "STATION", "MEDIUM", ""),
        ("Cakung Barat", "REFERENCE", "MEDIUM", ""),
        ("Pulo Gebang", "STATION", "MEDIUM", ""),
        ("Ujung Menteng", "STATION", "HIGH", ""),
        ("Kalibaru Bekasi", "REFERENCE", "LOW", ""),
        ("Medan Satria", "STATION", "HIGH", ""),
        ("Harapan Baru", "REFERENCE", "MEDIUM", ""),
        ("Karang Satria", "REFERENCE", "MEDIUM", ""),
        ("Sumber Jaya", "REFERENCE", "LOW", ""),
        ("Cibitung", "EXISTING_CONNECTION", "HIGH", "KRL Cibitung"),
        ("Wanajaya", "REFERENCE", "MEDIUM", ""),
        ("Cikarang", "EXISTING_CONNECTION", "HIGH", "KRL Cikarang"),
    ],
)

add(
    id="MRT_4",
    mode="mrt",
    name="MRT Fase 4 Fatmawati–TMII",
    short="MRT 4",
    from_node="Fatmawati",
    to_node="TMII",
    status="MASTERPLAN",
    structure="UNDER_REVIEW",
    structure_historical="UG → DEEP UG → ELEVATED",
    structure_latest="FULL UNDERGROUND",
    source="MRT Jakarta Fase 4 concept",
    source_year=2024,
    source_type="OFFICIAL_MASTERPLAN",
    geometry_confidence="MEDIUM",
    alignment_confidence="MEDIUM",
    digitization_level="L3",
    digitization_method="DOCUMENT_RECONSTRUCTION + ROAD_REFERENCE",
    passenger_status="PASSENGER_PROPOSED",
    road_refs=["Jalan Pangeran Antasari", "Jalan Tahi Bonar Simatupang", "Jalan Raya Bogor"],
    spine=[
        [106.79246, -6.29247],
        [106.8080, -6.2910],
        [106.8220, -6.2880],
        [106.8320, -6.2780],
        [106.83865, -6.30969],
        [106.8520, -6.3080],
        [106.8680, -6.3070],
        [106.8760, -6.3090],
        [106.88440, -6.30955],
        [106.88058, -6.29290],
    ],
    nodes=[
        ("Fatmawati", "EXISTING_CONNECTION", "HIGH", "MRT existing"),
        ("Antasari", "STATION", "HIGH", ""),
        ("Ampera", "STATION", "HIGH", ""),
        ("Warung Jati", "STATION", "MEDIUM", ""),
        ("Tanjung Barat", "STATION", "HIGH", "dekat KRL Tanjung Barat"),
        ("Ranco", "STATION", "MEDIUM", ""),
        ("Raya Bogor", "STATION", "MEDIUM", "nomenklatur koridor, bukan Pasar Minggu"),
        ("Tanah Merdeka", "STATION", "MEDIUM", ""),
        ("Kampung Rambutan", "EXISTING_CONNECTION", "HIGH", "interchange LRT Jabodebek"),
        ("TMII", "EXISTING_CONNECTION", "HIGH", "LRT Jabodebek"),
    ],
)

add(
    id="LRT_JKT_1B",
    mode="lrt",
    name="LRT Jakarta 1B Velodrome–Manggarai",
    short="LRT Jakarta 1B",
    from_node="Velodrome",
    to_node="Manggarai",
    status="CONSTRUCTION",
    structure="ELEVATED",
    source="PT LRT Jakarta",
    source_year=2025,
    source_type="OFFICIAL_OPERATOR",
    geometry_confidence="HIGH",
    alignment_confidence="MEDIUM",
    digitization_level="L3",
    digitization_method="DOCUMENT_RECONSTRUCTION + ROAD_REFERENCE",
    passenger_status="PASSENGER_CONFIRMED",
    status_note="CONSTRUCTION_COMPLETED / PRE_OPERATIONAL sesuai sumber runtime. Bukan existing operasional tanpa validasi.",
    road_refs=["Jalan Pemuda", "Jalan Pramuka"],
    spine=[
        [106.89122, -6.19193],
        [106.8860, -6.1950],
        [106.8720, -6.1960],
        [106.8600, -6.1980],
        [106.8580, -6.2060],
        [106.85025, -6.21110],
    ],
    nodes=[
        ("Velodrome", "EXISTING_CONNECTION", "HIGH", "LRT Jakarta S existing"),
        ("Rawamangun", "STATION", "HIGH", "Pemuda Barat / Rawamangun"),
        ("Pramuka BPKP", "STATION", "HIGH", ""),
        ("Pasar Pramuka", "STATION", "HIGH", ""),
        ("Matraman", "STATION", "HIGH", "dekat KRL Matraman"),
        ("Manggarai", "EXISTING_CONNECTION", "HIGH", "KRL Manggarai"),
    ],
)

add(
    id="LRT_JKT_1C",
    mode="lrt",
    name="LRT Jakarta 1C Manggarai–Dukuh Atas",
    short="LRT Jakarta 1C",
    from_node="Manggarai",
    to_node="Dukuh Atas BNI",
    status="PLANNED",
    structure="ELEVATED",
    source="PT LRT Jakarta",
    source_year=2024,
    source_type="OFFICIAL_MASTERPLAN",
    geometry_confidence="MEDIUM",
    alignment_confidence="MEDIUM",
    digitization_level="L2",
    digitization_method="DOCUMENT_RECONSTRUCTION",
    passenger_status="PASSENGER_PROPOSED",
    length_source_km=2.4,
    road_refs=[],
    spine=[
        [106.85025, -6.21110],
        [106.8380, -6.2070],
        [106.82554, -6.20480],
    ],
    nodes=[
        ("Manggarai", "EXISTING_CONNECTION", "HIGH", ""),
        ("Dukuh Atas BNI", "EXISTING_CONNECTION", "HIGH", "LRT Jabodebek existing; jangan invent stasiun antara"),
    ],
)

add(
    id="LRT_JKT_2A",
    mode="lrt",
    name="LRT Jakarta 2A Kelapa Gading–JIS",
    short="LRT Jakarta 2A",
    from_node="Kelapa Gading",
    to_node="JIS",
    status="PLANNED",
    structure="ELEVATED",
    source="PT LRT Jakarta",
    source_year=2024,
    source_type="OFFICIAL_MASTERPLAN",
    geometry_confidence="MEDIUM",
    alignment_confidence="MEDIUM",
    digitization_level="L3",
    digitization_method="DOCUMENT_RECONSTRUCTION + ROAD_REFERENCE",
    passenger_status="PASSENGER_PROPOSED",
    length_source_km=8.2,
    road_refs=["Jalan Yos Sudarso", "Jalan Boulevard Selatan"],
    spine=[
        [106.91414, -6.15721],
        [106.9060, -6.1530],
        [106.8980, -6.1460],
        [106.8900, -6.1350],
        [106.8800, -6.1240],
        [106.8700, -6.1180],
        [106.86096, -6.12507],
    ],
    nodes=[
        ("Kelapa Gading", "EXISTING_CONNECTION", "HIGH", "LRT Jakarta S terminus"),
        ("Kelapa Nias", "STATION", "MEDIUM", ""),
        ("Boulevard Gading", "STATION", "MEDIUM", ""),
        ("Sunter Timur", "STATION", "MEDIUM", ""),
        ("Gelanggang Remaja", "STATION", "MEDIUM", ""),
        ("Sunter Barat", "STATION", "MEDIUM", ""),
        ("JIS", "STATION", "HIGH", "Danau Sunter Barat / JIS"),
    ],
)

add(
    id="LRT_JKT_2B",
    mode="lrt",
    name="LRT Jakarta 2B Velodrome–Klender",
    short="LRT Jakarta 2B",
    from_node="Velodrome",
    to_node="Klender",
    status="PLANNED",
    structure="ELEVATED",
    source="PT LRT Jakarta",
    source_year=2024,
    source_type="OFFICIAL_MASTERPLAN",
    geometry_confidence="LOW",
    alignment_confidence="LOW",
    digitization_level="L2",
    digitization_method="DOCUMENT_RECONSTRUCTION",
    passenger_status="PASSENGER_PROPOSED",
    length_source_km=4.5,
    expected_station_count=4,
    road_refs=["Jalan I Gusti Ngurah Rai", "Jalan Bekasi Timur"],
    spine=[
        [106.89122, -6.19193],
        [106.9050, -6.1950],
        [106.9100, -6.2050],
        [106.89865, -6.21324],
    ],
    nodes=[
        ("Velodrome", "EXISTING_CONNECTION", "HIGH", ""),
        ("Kayu Putih", "STATION", "LOW", "indikatif: kawasan Kayu Putih sepanjang Pemuda / Ngurah Rai; nama 4 stasiun resmi belum lengkap"),
        ("Pulogadung", "STATION", "MEDIUM", "indikatif: simpul Terminal Pulogadung / I Gusti Ngurah Rai"),
        ("Klender", "STATION", "MEDIUM", "dekat KRL Klender; nama 4 stasiun belum lengkap"),
    ],
)

add(
    id="LRT_JKT_3A",
    mode="lrt",
    name="LRT Jakarta 3A JIS–Rajawali",
    short="LRT Jakarta 3A",
    from_node="JIS",
    to_node="Rajawali",
    status="PLANNED",
    structure="ELEVATED",
    source="PT LRT Jakarta",
    source_year=2024,
    source_type="OFFICIAL_MASTERPLAN",
    geometry_confidence="LOW",
    alignment_confidence="LOW",
    digitization_level="L2",
    digitization_method="DOCUMENT_RECONSTRUCTION",
    passenger_status="PASSENGER_PROPOSED",
    length_source_km=5.6,
    expected_station_count=4,
    road_refs=["Jalan Yos Sudarso", "Jalan Gunung Sahari Raya"],
    spine=[
        [106.86096, -6.12507],
        [106.8480, -6.1220],
        [106.8350, -6.1260],
        [106.8280, -6.1380],
        [106.83718, -6.14631],
    ],
    nodes=[
        ("JIS", "EXISTING_CONNECTION", "HIGH", ""),
        ("Pademangan", "STATION", "LOW", "indikatif: kawasan Sunter / Pademangan — bukan nama station final"),
        ("Gunung Sahari", "STATION", "LOW", "indikatif: koridor Jalan Gunung Sahari Raya"),
        ("Rajawali", "STATION", "MEDIUM", "dekat KRL Rajawali"),
    ],
)

add(
    id="LRT_JKT_3B",
    mode="lrt",
    name="LRT Jakarta 3B Klender–Halim",
    short="LRT Jakarta 3B",
    from_node="Klender",
    to_node="Halim",
    status="PLANNED",
    structure="ELEVATED",
    source="PT LRT Jakarta",
    source_year=2024,
    source_type="OFFICIAL_MASTERPLAN",
    geometry_confidence="LOW",
    alignment_confidence="LOW",
    digitization_level="L2",
    digitization_method="DOCUMENT_RECONSTRUCTION",
    passenger_status="PASSENGER_PROPOSED",
    length_source_km=4.9,
    expected_station_count=4,
    road_refs=["Jalan Pahlawan Revolusi", "Jalan Otto Iskandar Dinata"],
    spine=[
        [106.89865, -6.21324],
        [106.9027, -6.2380],
        [106.88728, -6.24585],
    ],
    nodes=[
        ("Klender", "EXISTING_CONNECTION", "HIGH", ""),
        ("Pondok Bambu", "STATION", "MEDIUM", ""),
        ("Halim", "EXISTING_CONNECTION", "HIGH", "LRT Jabodebek Halim — interchange candidate"),
    ],
)

add(
    id="LRT_BOGOR",
    mode="lrt",
    name="LRT Jabodebek perpanjangan Harjamukti–Baranangsiang",
    short="LRT Bogor",
    from_node="Harjamukti",
    to_node="Baranangsiang",
    status="UNDER_STUDY",
    structure="ELEVATED",
    source="Studi trase LRT Jabodebek Bogor",
    source_year=2022,
    source_type="OFFICIAL_MASTERPLAN",
    geometry_confidence="LOW",
    alignment_confidence="LOW",
    digitization_level="L2",
    digitization_method="DOCUMENT_RECONSTRUCTION",
    passenger_status="PASSENGER_PROPOSED",
    road_refs=["Jalan Tol Jakarta–Bogor–Ciawi", "Jalan Raya Bogor"],
    spine=[
        [106.89569, -6.37389],
        [106.8880, -6.3850],
        [106.8900, -6.4200],
        [106.8700, -6.4600],
        [106.8580, -6.5300],
        [106.8620, -6.5600],
        [106.8400, -6.5850],
        [106.8160, -6.6010],
    ],
    nodes=[
        ("Harjamukti", "EXISTING_CONNECTION", "HIGH", "LRT Jabodebek existing terminus; jangan ulang Cawang–Harjamukti"),
        ("Cisalak", "STATION", "LOW", "indikatif: simpang Jagorawi Cisalak"),
        ("Cimanggis", "STATION", "MEDIUM", "kawasan Cimanggis; nomenklatur dapat berubah"),
        ("Gunung Putri", "STATION", "MEDIUM", "kawasan Gunung Putri di koridor Jagorawi, bukan stasiun KRL existing"),
        ("Cibinong", "STATION", "MEDIUM", "kawasan Cibinong di Jagorawi; pertukaran kandidat dengan KRL cabang Nambo"),
        ("Sirkuit Sentul", "STATION", "LOW", "indikatif: kawasan Sirkuit Sentul"),
        ("Sentul City", "STATION", "LOW", "indikatif: kawasan Sentul City"),
        ("Baranangsiang", "STATION", "MEDIUM", "terminus Terminal Baranangsiang; UNDER STUDY"),
    ],
)

add(
    id="LRT_09",
    mode="lrt",
    name="LRT 09 Jagakarsa–Cileungsi",
    short="LRT 09",
    from_node="Jagakarsa",
    to_node="Cileungsi",
    status="MASTERPLAN",
    structure="NOT_SPECIFIED",
    source="Masterplan LRT koridor 09",
    source_year=2020,
    source_type="SECONDARY_REFERENCE",
    geometry_confidence="LOW",
    alignment_confidence="LOW",
    digitization_level="L2",
    digitization_method="DOCUMENT_RECONSTRUCTION",
    passenger_status="UNCERTAIN",
    road_refs=[],
    spine=[
        [106.8282, -6.3300],
        [106.89569, -6.37389],
        [106.9920, -6.4020],
    ],
    nodes=[
        ("Jagakarsa", "STATION", "MEDIUM", "terminus kawasan Jagakarsa"),
        ("Harjamukti", "EXISTING_CONNECTION", "HIGH", "kawasan Cibubur / Harjamukti — interchange LRT Jabodebek"),
        ("Transyogi", "STATION", "LOW", "indikatif: koridor Transyogi antara Cibubur dan Cileungsi"),
        ("Nagrak", "STATION", "LOW", "indikatif: kawasan Nagrak (peta JUTPI koridor Depok–Cileungsi)"),
        ("Cileungsi", "STATION", "MEDIUM", "terminus kawasan Cileungsi"),
    ],
)

CORRIDORS = C
