export const SURVEY_TEAM = "Geo Unjuk Kebolehan";
export const SURVEY_HASHTAG = "geounjukkebolehan";
export const SURVEY_USERS = [
  "fabyanismail",
  "lendwils",
  "rayislamy",
  "sandi1406082006",
] as const;
export const SURVEY_TITLES = [
  "Simpang Lenteng Agung titik strategis penyebab kemacetan yang disebabkan angkot",
  "Hunian apartemen terbaru: Mahata Tanjung Barat dekat dengan TOD KRL & Transjakarta non BRT",
  "Halte non BRT Transjakarta Tanjung Barat yang selalu ramai",
  "Simpang Ragunan Ar-Raudhah TB Simatupang, Salah satu penyebab macet horor",
  "Simpang Pejaten, salah satu akar kemacetan cukup parah di Jakarta Selatan",
  "Buncit Indah, Kawasan Strategis yang cukup asik untuk nongkrong",
  "Simpang Warung Buncit, salah satu titik kemacetan di jakarta selatan",
  "Pertigaan kemang utara, jalanan sempit, volume kendaraan tinggi karena banyak perumahan",
  "Tanah & Bangunan terbengkalai dan cukup besar di Daerah Kemang Utara, bagus untuk kawasan usaha",
  "Perempatan kemang raya, salah satu biang kerok kemacetan parah di Jakarta Selatan",
  "Sentra Kuliner Malam di dekat daerah Kemang: Jalan Bangka Raya salah satu biang kerok kemacetan.",
  "Pasar malam dadakan di Jalan Bangka Raya (spesial HUT RI ke-81)",
  "Simpang Mampang, menjadi salah satu persimpangan dengan predikat tersibuk di Jakarta Selatan",
  "Layanan AMARI (Angkutan Malam Hari) Transjakarta koridor 13, yang aktif dari pukul 22.00-05.00",
  "Pertigaan jalan raya tapos dari arah cibinong, efek kemacetan cukup parah di kab bogor",
  "Kemacetan kabupaten bogor didepan smpn 1 cibinong tanggal 18 agustus 2026, salah satu titik kemacetan yang cukup parah dikabupaten bogot",
  "Titik macet di area gunung putri jl. Mayor oking citereup, macet disebabkan oleh persimpangan antara pintu tol gn. Putri dan akses masuk pabrik indosement tigo roda",
  "Pertigaan pesing, akar kemacetan mengular di Jakarta barat",
  "Perlintasan kereta roxy",
  "Perempatan grogol",
  "Persimpangan harmoni",
  "Bundaran golf island",
  "Stasiun Citayam, Stasiun yang berpotensi untuk membuka jalur percabangan kearah Parungpanjang via Parung",
  "titik kemacetan pada jalan raya mayor oking jaya atmaja, kabupaten cibinong. Kemacetan disebabkan oleh persimpangan dengan jl. H. Moh Ashari ditambah dengan volume kendaraan yang ramai",
  "Pertigaan ke arah parung dari citayam dan pancoranmas banyak perumahan sehingga kepadatan",
  "Jalan raya citayam-parung, satu satunya akses dari arah citayam kearah parung dsk",
  "Tugu macan pertigaan arah parung dari citayam salah satu akar kemacetan di sekitar citayam",
  "Titik macet di jalan raya mayor oking jaya atmaja, kabupaten cibinong. Kemacetan disebabkan oleh penyempitan jalan menjadi satu arah",
  "Persimpangan Cideng Barat",
  "Persimpangan RS Tarakan",
  "Simpang siur di Persimpangan Tomang",
  "TJ Central park & gerbang masuk podomoro land",
  "Titik kemacetan pada jalan baru puspa negara, kab cibinong. Kemacetan disebabkan oleh persimpangan dengan jalan mayor oking citeurep.",
  "Pertigaan PTB Angke - Peternakan",
  "Kecamatan parung panjang cukup eamai dan strategis untuk percabangan rel ke arah citayam",
  "Simpang jalan kapuk raya",
  "Perempatan di jalan kapuk raya Samping Banjir kanal barat",
  "Pertigaan Daan Mogot - Pendongkelan",
  "Titik kemacetan di jalan transyogi, cibubur. Kemacetan disebabkan oleh adanya persimpangan dengan jalan raya kota wisata yang merupakan akses kedalam komplek kota wisata yang merupakan destinasi wisata bagi banyak masyarakat jakarta",
  "Bundaran PIK (Tzu Chi, PIK AVENUE)",
  "Persimpangan jalan pantura pulo gadung yang strategis menuju harapan indah",
  "Pertigaan PTB Angke - Peternakan",
  "Kecamatan parung panjang cukup eamai dan strategis untuk percabangan rel ke arah citayam",
  "Simpang jalan kapuk raya",
  "Perempatan di jalan kapuk raya Samping Banjir kanal barat",
  "Pertigaan Daan Mogot - Pendongkelan",
  "Titik kemacetan di jalan transyogi, cibubur. Kemacetan disebabkan oleh adanya persimpangan dengan jalan raya kota wisata yang merupakan akses kedalam komplek kota wisata yang merupakan destinasi wisata bagi banyak masyarakat jakarta",
  "Bundaran PIK (Tzu Chi, PIK AVENUE)",
  "Persimpangan jalan pantura pulo gadung yang strategis menuju harapan indah",
  "Jalan pantura arah ke pulo gadung dari bekasi sebagai jalut padat menantang",
  "Kota harapan indah bekasi, titik strategis operasional busway ke arah pulo gadung",
  "Terminal pulo gadung sebagai titik aktivasi koridor",
  "Terminal Pulo Gebang: titik awal koridor Kota Harapan Indah menuju Pulo Gadung",
  "Lalu lintas parung yang harus dibenahi dengan transportasi massal",
  "Pasar parung sebagau lokasi strategis stasiun perpanjangan rel kereta aoi citayam-parung panjang",
  "Titik kemacetan terjadi pada jalan Tlajung Udik, gn putri, kab cibinong. Kemacetan disebabkan oleh dua persimpangan yang berdekatan",
  "Titik kemacetan di jalan Narogong, gunung putri, kab. Cileungsi",
  "Titik kemacetan di jalan raya narogong, gunung putri, cileungsi. Kemacetan disebabkan oleh ditutupnya akses menuju jembatan dikarenakan jembatan rubuh.",
  "Titik kemacetan di jalan raya kelapa nunggal, kec kelapa nunggal.",
  "Perempatan Gunung Sahari - Angkasa - Samanhudi",
  "Putaran jalan sunter boulevard",
  "Titik keramaian dijalan raya klapa nunggal, cileungsi, kab. Bogor.",
  "Titik kemacetan dijalan raya kelapa nunggal, cileungsi, kab. Bogor",
  "Persimpangan Jalan Boulevard Hijau Raya, Jalan Boulevard Harapan Indah, dan Jalan Duta Bumi Raya",
  "Bundaran utama koridor Kota Harapan Indah 2",
  "Persimpangan Jalan Raya Tarumajaya dan Jalan Pusaka Rakyat dekat bundaran Kota Harapan Indah",
  "Gerbang Tol Tarumajaya",
  "Kawasan Marunda Center",
  "Titik aktivitas masyarakat di jalan raya klapa nunggal.",
  "Pertigaan Jalan Marunda Raya menuju STIP (akses Jalan Marunda Makmur / Rusun Marunda)",
  "Simpang Pertigaan Akses Marunda",
  "Jalan Sulawesi / Jalan Pelabuhan (akses Pos 1 Pelabuhan Tanjung Priok)",
  "Pertigaan Ketel/RE Martadinata/Ancol Karnaval",
  "Pertigaan Tarumajaya dan kantor Tarumajaya",
  "Potensi integrasi Stasiun dan Terminal Tj priok sebagai pengurai kemacetan",
  "Permasalahan pertigaan Enggano dan potensi ekspansi KRL pink line",
  "Halte TJ Simpang Cempaka Mas (Jalan letjen suprapto dan perintis kemerdekaan)",
  "U turn Kelapa gading boulevard (Samping MOI)",
  "Jalan Danau Sunter Utara (sekitar halte busway/Minitrans, perempatan pompa air Danau Sunter, dan Pizza Hut),",
  "Jalan landas pacu timur / Halte Kemayoran landas Pacu",
] as const;
export const SURVEY_REJECTED = [
  "Titik macet di area gunung putri jl. Mayor oking citeurep. Kemacetan disebabkan oleh persimpangangan pintu akses pabrik indosement semen tiga roda",
  "Perempatan Gunung Sahari - Angkasa - Samanhudi",
] as const;
