/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalisisRouteImport } from './routes/analisis'
import { Route as SimulasiRouteImport } from './routes/simulasi'
import { Route as ApiPropertiesRouteImport } from './routes/api/properties'
import { Route as ApiPropertyAiInsightsRouteImport } from './routes/api/property-ai-insights'
import { Route as ApiPropertyPriceZonesRouteImport } from './routes/api/property-price-zones'
import { Route as ApiSurveyActivitiesRouteImport } from './routes/api/survey-activities'
import { Route as ApiMapidSplatRouteImport } from './routes/api/mapid/$'
import { Route as ApiPropertiesIdRouteImport } from './routes/api/properties/$id'
import { Route as ApiCorridorsIdPriceDistributionRouteImport } from './routes/api/corridors/$id/price-distribution'
import { Route as ApiCorridorsIdPropertiesRouteImport } from './routes/api/corridors/$id/properties'
import { Route as ApiCorridorsIdPropertySummaryRouteImport } from './routes/api/corridors/$id/property-summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisisRoute = AnalisisRouteImport.update({
  id: '/analisis',
  path: '/analisis',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulasiRoute = SimulasiRouteImport.update({
  id: '/simulasi',
  path: '/simulasi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertiesRoute = ApiPropertiesRouteImport.update({
  id: '/api/properties',
  path: '/api/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertyAiInsightsRoute = ApiPropertyAiInsightsRouteImport.update({
  id: '/api/property-ai-insights',
  path: '/api/property-ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertyPriceZonesRoute = ApiPropertyPriceZonesRouteImport.update({
  id: '/api/property-price-zones',
  path: '/api/property-price-zones',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSurveyActivitiesRoute = ApiSurveyActivitiesRouteImport.update({
  id: '/api/survey-activities',
  path: '/api/survey-activities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapidSplatRoute = ApiMapidSplatRouteImport.update({
  id: '/api/mapid/$',
  path: '/api/mapid/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertiesIdRoute = ApiPropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPropertiesRoute,
} as any)
const ApiCorridorsIdPriceDistributionRoute =
  ApiCorridorsIdPriceDistributionRouteImport.update({
    id: '/api/corridors/$id/price-distribution',
    path: '/api/corridors/$id/price-distribution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCorridorsIdPropertiesRoute =
  ApiCorridorsIdPropertiesRouteImport.update({
    id: '/api/corridors/$id/properties',
    path: '/api/corridors/$id/properties',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCorridorsIdPropertySummaryRoute =
  ApiCorridorsIdPropertySummaryRouteImport.update({
    id: '/api/corridors/$id/property-summary',
    path: '/api/corridors/$id/property-summary',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRoute
  '/simulasi': typeof SimulasiRoute
  '/api/properties': typeof ApiPropertiesRouteWithChildren
  '/api/property-ai-insights': typeof ApiPropertyAiInsightsRoute
  '/api/property-price-zones': typeof ApiPropertyPriceZonesRoute
  '/api/survey-activities': typeof ApiSurveyActivitiesRoute
  '/api/mapid/$': typeof ApiMapidSplatRoute
  '/api/properties/$id': typeof ApiPropertiesIdRoute
  '/api/corridors/$id/price-distribution': typeof ApiCorridorsIdPriceDistributionRoute
  '/api/corridors/$id/properties': typeof ApiCorridorsIdPropertiesRoute
  '/api/corridors/$id/property-summary': typeof ApiCorridorsIdPropertySummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRoute
  '/simulasi': typeof SimulasiRoute
  '/api/properties': typeof ApiPropertiesRouteWithChildren
  '/api/property-ai-insights': typeof ApiPropertyAiInsightsRoute
  '/api/property-price-zones': typeof ApiPropertyPriceZonesRoute
  '/api/survey-activities': typeof ApiSurveyActivitiesRoute
  '/api/mapid/$': typeof ApiMapidSplatRoute
  '/api/properties/$id': typeof ApiPropertiesIdRoute
  '/api/corridors/$id/price-distribution': typeof ApiCorridorsIdPriceDistributionRoute
  '/api/corridors/$id/properties': typeof ApiCorridorsIdPropertiesRoute
  '/api/corridors/$id/property-summary': typeof ApiCorridorsIdPropertySummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRoute
  '/simulasi': typeof SimulasiRoute
  '/api/properties': typeof ApiPropertiesRouteWithChildren
  '/api/property-ai-insights': typeof ApiPropertyAiInsightsRoute
  '/api/property-price-zones': typeof ApiPropertyPriceZonesRoute
  '/api/survey-activities': typeof ApiSurveyActivitiesRoute
  '/api/mapid/$': typeof ApiMapidSplatRoute
  '/api/properties/$id': typeof ApiPropertiesIdRoute
  '/api/corridors/$id/price-distribution': typeof ApiCorridorsIdPriceDistributionRoute
  '/api/corridors/$id/properties': typeof ApiCorridorsIdPropertiesRoute
  '/api/corridors/$id/property-summary': typeof ApiCorridorsIdPropertySummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analisis'
    | '/simulasi'
    | '/api/properties'
    | '/api/property-ai-insights'
    | '/api/property-price-zones'
    | '/api/survey-activities'
    | '/api/mapid/$'
    | '/api/properties/$id'
    | '/api/corridors/$id/price-distribution'
    | '/api/corridors/$id/properties'
    | '/api/corridors/$id/property-summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analisis'
    | '/simulasi'
    | '/api/properties'
    | '/api/property-ai-insights'
    | '/api/property-price-zones'
    | '/api/survey-activities'
    | '/api/mapid/$'
    | '/api/properties/$id'
    | '/api/corridors/$id/price-distribution'
    | '/api/corridors/$id/properties'
    | '/api/corridors/$id/property-summary'
  id:
    | '__root__'
    | '/'
    | '/analisis'
    | '/simulasi'
    | '/api/properties'
    | '/api/property-ai-insights'
    | '/api/property-price-zones'
    | '/api/survey-activities'
    | '/api/mapid/$'
    | '/api/properties/$id'
    | '/api/corridors/$id/price-distribution'
    | '/api/corridors/$id/properties'
    | '/api/corridors/$id/property-summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalisisRoute: typeof AnalisisRoute
  SimulasiRoute: typeof SimulasiRoute
  ApiPropertiesRoute: typeof ApiPropertiesRouteWithChildren
  ApiPropertyAiInsightsRoute: typeof ApiPropertyAiInsightsRoute
  ApiPropertyPriceZonesRoute: typeof ApiPropertyPriceZonesRoute
  ApiSurveyActivitiesRoute: typeof ApiSurveyActivitiesRoute
  ApiMapidSplatRoute: typeof ApiMapidSplatRoute
  ApiCorridorsIdPriceDistributionRoute: typeof ApiCorridorsIdPriceDistributionRoute
  ApiCorridorsIdPropertiesRoute: typeof ApiCorridorsIdPropertiesRoute
  ApiCorridorsIdPropertySummaryRoute: typeof ApiCorridorsIdPropertySummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisis': {
      id: '/analisis'
      path: '/analisis'
      fullPath: '/analisis'
      preLoaderRoute: typeof AnalisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulasi': {
      id: '/simulasi'
      path: '/simulasi'
      fullPath: '/simulasi'
      preLoaderRoute: typeof SimulasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/properties': {
      id: '/api/properties'
      path: '/api/properties'
      fullPath: '/api/properties'
      preLoaderRoute: typeof ApiPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/property-ai-insights': {
      id: '/api/property-ai-insights'
      path: '/api/property-ai-insights'
      fullPath: '/api/property-ai-insights'
      preLoaderRoute: typeof ApiPropertyAiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/property-price-zones': {
      id: '/api/property-price-zones'
      path: '/api/property-price-zones'
      fullPath: '/api/property-price-zones'
      preLoaderRoute: typeof ApiPropertyPriceZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/survey-activities': {
      id: '/api/survey-activities'
      path: '/api/survey-activities'
      fullPath: '/api/survey-activities'
      preLoaderRoute: typeof ApiSurveyActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mapid/$': {
      id: '/api/mapid/$'
      path: '/api/mapid/$'
      fullPath: '/api/mapid/$'
      preLoaderRoute: typeof ApiMapidSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/properties/$id': {
      id: '/api/properties/$id'
      path: '/$id'
      fullPath: '/api/properties/$id'
      preLoaderRoute: typeof ApiPropertiesIdRouteImport
      parentRoute: typeof ApiPropertiesRoute
    }
    '/api/corridors/$id/price-distribution': {
      id: '/api/corridors/$id/price-distribution'
      path: '/api/corridors/$id/price-distribution'
      fullPath: '/api/corridors/$id/price-distribution'
      preLoaderRoute: typeof ApiCorridorsIdPriceDistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/corridors/$id/properties': {
      id: '/api/corridors/$id/properties'
      path: '/api/corridors/$id/properties'
      fullPath: '/api/corridors/$id/properties'
      preLoaderRoute: typeof ApiCorridorsIdPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/corridors/$id/property-summary': {
      id: '/api/corridors/$id/property-summary'
      path: '/api/corridors/$id/property-summary'
      fullPath: '/api/corridors/$id/property-summary'
      preLoaderRoute: typeof ApiCorridorsIdPropertySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiPropertiesRouteChildren {
  ApiPropertiesIdRoute: typeof ApiPropertiesIdRoute
}

const ApiPropertiesRouteChildren: ApiPropertiesRouteChildren = {
  ApiPropertiesIdRoute: ApiPropertiesIdRoute,
}

const ApiPropertiesRouteWithChildren = ApiPropertiesRoute._addFileChildren(
  ApiPropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalisisRoute: AnalisisRoute,
  SimulasiRoute: SimulasiRoute,
  ApiPropertiesRoute: ApiPropertiesRouteWithChildren,
  ApiPropertyAiInsightsRoute: ApiPropertyAiInsightsRoute,
  ApiPropertyPriceZonesRoute: ApiPropertyPriceZonesRoute,
  ApiSurveyActivitiesRoute: ApiSurveyActivitiesRoute,
  ApiMapidSplatRoute: ApiMapidSplatRoute,
  ApiCorridorsIdPriceDistributionRoute: ApiCorridorsIdPriceDistributionRoute,
  ApiCorridorsIdPropertiesRoute: ApiCorridorsIdPropertiesRoute,
  ApiCorridorsIdPropertySummaryRoute: ApiCorridorsIdPropertySummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
